### ISSUE TITLE
the firefly icon should be inside the moroder folder

### ISSUE THREAD

**Issue by ludovicosilvestri** [ludovicosilvestri/moroder#10]
otherwise you'll get an error message when opening all_spim_classes.proj on any other computer. Now it seems to be in downloads folder

**Comment by CarolineMuellenbroich** [comment]
done in the real world, not solved on github

On Tue, Nov 24, 2015 at 5:50 PM, Ludovico Silvestri <
notifications@github.com> wrote:

> otherwise you'll get an error message when opening all_spim_classes.proj
> on any other computer. Now it seems to be in downloads folder
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ludovicosilvestri/moroder/issues/10.

## 

Caroline Müllenbroich, PhD
Biophysics
LENS- European Laboratory for Non-Linear Spectroscopy
University of Florence
Italy

**Comment by ludovicosilvestri** [comment]
mmm probably there is some broken link in the project

**Comment by CarolineMuellenbroich** [comment]
didnt pushy pully yet
I mean i literally just did it

On Tue, Nov 24, 2015 at 5:53 PM, Ludovico Silvestri <
notifications@github.com> wrote:

> mmm probably there is some broken link in the project
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ludovicosilvestri/moroder/issues/10#issuecomment-159336592
> .

## 

Caroline Müllenbroich, PhD
Biophysics
LENS- European Laboratory for Non-Linear Spectroscopy
University of Florence
Italy

**Comment by ludovicosilvestri** [comment]
Grande!

Sorry for the intrusion, but I wanted to check the version of murmex. It
seems that the newest has some conflicts with the older! I will investigate
with the maestro

Ludo

2015-11-24 17:55 GMT+01:00 Caroline Muellenbroich notifications@github.com
:

> didnt pushy pully yet
> I mean i literally just did it
> 
> On Tue, Nov 24, 2015 at 5:53 PM, Ludovico Silvestri <
> notifications@github.com> wrote:
> 
> > mmm probably there is some broken link in the project
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/ludovicosilvestri/moroder/issues/10#issuecomment-159336592
> > 
> > .
> 
> ## 
> 
> Caroline Müllenbroich, PhD
> Biophysics
> LENS- European Laboratory for Non-Linear Spectroscopy
> University of Florence
> Italy
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ludovicosilvestri/moroder/issues/10#issuecomment-159337562
> .

## 

Ludovico Silvestri, PhD

National Institute of Optics (INO-CNR)
European Laboratory for Non-linear Spectroscopy
Via Nello Carrara, 1
50019 Sesto Fiorentino (FI)
Italy
tel: +390554572504
lab: +390554572513
lab: +390554572019

**Comment by CarolineMuellenbroich** [comment]
luke
I am your father

sorry for this intrusion

On Tue, Nov 24, 2015 at 5:55 PM, Caroline Muellenbroich <
muellenbroich@lens.unifi.it> wrote:

> didnt pushy pully yet
> I mean i literally just did it
> 
> On Tue, Nov 24, 2015 at 5:53 PM, Ludovico Silvestri <
> notifications@github.com> wrote:
> 
> > mmm probably there is some broken link in the project
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ludovicosilvestri/moroder/issues/10#issuecomment-159336592
> > .
> 
> ## 
> 
> Caroline Müllenbroich, PhD
> Biophysics
> LENS- European Laboratory for Non-Linear Spectroscopy
> University of Florence
> Italy

## 

Caroline Müllenbroich, PhD
Biophysics
LENS- European Laboratory for Non-Linear Spectroscopy
University of Florence
Italy
